### ISSUE TITLE
Hi, It's still not response, I record a video and you can watch it

### ISSUE THREAD

**Issue by yuanhoujun** [skalio/native-drag-and-drop#2]
https://user-images.githubusercontent.com/7424397/175449390-e1b1fbf1-cf01-41c4-af19-f23ba77fc351.mov

```
#57     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
#58     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#59     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:535:18)
#60     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#61     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#62     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#63     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#64     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#65     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#66     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#67     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#68     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#69     RenderView.hitTest (package:flutter/src/rendering/view.dart:185:14)
#70     RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:538:16)
#71     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:352:7)
#72     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#73     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#74     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#75     _rootRunUnary (dart:async/zone.dart:1442:13)
#76     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#77     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#78     _invoke1 (dart:ui/hooks.dart:170:10)
#79     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#80     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Cannot hit test a render box that has never been laid out.
The hitTest() method was called on this RenderBox: RenderErrorBox#6f65d NEEDS-LAYOUT NEEDS-PAINT:
  creator: ErrorWidget-[#84649] ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#0001b ink renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ← AnimatedPhysicalModel ← ⋯
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body
  constraints: MISSING
  size: MISSING
Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested.
If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).
#0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:2430:11)
#1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2461:6)
#2      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2824:25)
#3      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:785:31)
#4      RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2819:33)
#5      RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:413:12)
#6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#7      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#9      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#10     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#11     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1918:18)
#12     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#14     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#16     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#18     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3349:31)
#19     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2824:25)
#20     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:785:31)
#21     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2819:33)
#22     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:602:12)
#23     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#24     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#26     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#27     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2797:22)
#28     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:785:31)
#29     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2791:19)
#30     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2777:12)
#31     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#32     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2797:22)
#33     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:785:31)
#34     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2791:19)
#35     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2777:12)
#36     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#37     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#38     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#39     _RenderFocusTrap.hitTest (package:flutter/src/widgets/routes.dart:2172:19)
#40     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#41     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#42     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#43     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#44     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3468:31)
#45     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#46     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#47     _RenderTheatre.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/overlay.dart:771:25)
#48     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:785:31)
#49     _RenderTheatre.hitTestChildren (package:flutter/src/widgets/overlay.dart:766:33)
#50     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#51     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#52     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#53     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#54     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#55     RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3566:17)
#56     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#57     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
#58     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#59     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:535:18)
#60     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#61     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#62     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#63     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#64     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#65     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#66     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#67     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#68     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2463:11)
#69     RenderView.hitTest (package:flutter/src/rendering/view.dart:185:14)
#70     RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:538:16)
#71     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:352:7)
#72     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#73     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#74     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#75     _rootRunUnary (dart:async/zone.dart:1442:13)
#76     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#77     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#78     _invoke1 (dart:ui/hooks.dart:170:10)
#79     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#80     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
```

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-CN)
    • Flutter version 3.0.1 at /Users/ouyangfeng/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ouyangfeng/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by leonx98** [comment]
Hey,
dragging into the application is not supported. Just out of the application but interesting error message. We're inspecting it now to find the cause.

**Comment by yuanhoujun** [comment]
But I also can't drag the image out, no responses. Just watch this video above.

**Comment by technolion** [comment]
Yes, we already found the problem and are working on it.

**Comment by leonx98** [comment]
@yuanhoujun We have released a new version. Hopefully the problem shouldn't appear anymore ;)
